# ===============================
# H2 Database Configuration
# ===============================

spring.datasource.url=jdbc:h2:mem:hrdb

spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=


# ===============================
# JPA / Hibernate Configuration
# ===============================

# Automatically create/update tables from entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console
spring.jpa.show-sql=true

# Format SQL output
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# H2 Console
# ===============================

# Enable H2 web console
spring.h2.console.enabled=true

# H2 console URL
spring.h2.console.path=/h2-console


# ===============================
# Server Configuration
# ===============================

server.port=8081
spring.application.name=hr
